### ISSUE TITLE
Make normalized plots

### ISSUE THREAD

**Issue by barthac** [EFerriss/Pynams#12]
Can you add a keyword into plot_area_profile that will normalize all the profiles to their maximum value. 
It might also be good to have a keyword that would normalize the distances so that you can easily plot two profiles from different crystals over each other.

**Comment by whtowbin** [comment]
Could you also add the wave number bounding window function from make_area_list applicable to plot_area_profile ?

**Comment by EFerriss** [comment]
Henry and I talked about this in person - I'm not planning to add those keywords in plot_area_profile, because you can just make the areas and then re-plot with the keyword axes=your axes handle to plot on the same figure as before. I will add the normalize keyword.

**Comment by EFerriss** [comment]
profile.plot_area_profile() now has keywords normalize_areas and normalize_positions Also, centered=False is now the default. 

And in my last comment, I was referring to the wavenumber bounds for making area, not the normalization keywords.
