### ISSUE TITLE
Change line thickness on baseline and spectrum plots

### ISSUE THREAD

**Issue by barthac** [EFerriss/Pynams#13]
I find it difficult to see exactly where the baseline is hitting the spectrum because the blue line is so thick. Is there a keyword to change the thickness for spec.get_area_under_curve?
I can do style = {'line width' : 1} for the show_baseline plots but this option doesn't exist for spec.get_area_under_curve.

Also, is there a way to do profile.get_area_under_curve since right now I have to loop over all the spectra in the profile.

**Comment by whtowbin** [comment]
For plotting the areas along a profile try plot_profile_area

fig, ax, ax_water = prof.plot_area_profile(centered=False, 
                                           show_water_ppm=False,
                                           #scaling_factor=3, 
                                           calibration='Bell',
                                           label=label)

**Comment by whtowbin** [comment]
prof.make_area_list(wn_low=3165, wn_high=3200) will make a list of areas in the profile. You can leave out the keywords if you don't want to select a sub area from your profile. 
If you use the key word "show_plot=True" you can make several figures that display the sub area you have selected. This is great if you have multiple peaks with the same baseline that you want to get the area for separately.

**Comment by barthac** [comment]
Ahh perfect, thanks!

**Comment by whtowbin** [comment]
If you want to do profiles normalized to the maximum value you can make your X positions prof.positions_microns and your Y positions prof.make_area_list(wn_low=3165, wn_high=3200)/max(prof.make_area_list(wn_low=3165, wn_high=3200)

**Comment by barthac** [comment]
Yeah that's what I've been doing, Elizabeth thought it would be good to include a keyword in there

**Comment by EFerriss** [comment]
Note in case you want the figure and axes handles for the plots showing the exact area returned to you: spectrum.get_area_under_curve(show_plot=True) returns 3 things: fig, ax, area, and when you do profile.make_area_list(), that just loops through all the spectra doing spectrum.get_area_curve() and gathers the resulting areas up into profile.areas.

I will make a keyword normalized (default=False) in profile.plot_area_profile to save you a tiny bit of hassle there.

**Comment by EFerriss** [comment]
Maybe the method names should be the same or similar for spectrum and profile, so spectrum.make_area() and profile.make_areas() instead of spectrum.get_area_under_curve() and profile.make_area_list(). Feelings?

**Comment by EFerriss** [comment]
Change in vocabulary made! Now spectrum.make_area() and profile.make_areas(). I will update the examples momentarily.
