### ISSUE TITLE
profile.diffusion1D

### ISSUE THREAD

**Issue by barthac** [EFerriss/Pynams#18]
I think profile.diffusion1D(peak_idx = ) is not working. Seems to work for plot_diffusion though.
Any ideas? I'm using it to plot the green shaded region of possible times on my diffusion profile.

**Comment by EFerriss** [comment]
Fixed!

I also added shift_water keyword to profile.plot_diffusion() and have the ylabel on that axis show the shift_water value if it's not equal to zero.
