### ISSUE TITLE
Plot Multiple Profiles on the Same Plot With Water Calibration

### ISSUE THREAD

**Issue by whtowbin** [EFerriss/Pynams#29]
Do You have any tips for plotting multiple multiple area profiles on the same plot but keeping the water ppm axis. 
I have been doing this by setting axes=ax but this gets rid of the water calibration. 

I would like to be able to compare profiles and to also make crude peak specific approximations using different area ranges.

**Comment by EFerriss** [comment]
The water ppm axis should not change relative to the main axis. Can you tell me more about how exactly changes? 

Check out [the example](https://github.com/EFerriss/Pynams/blob/master/EXAMPLES.ipynb) under the heading "Make area profiles".

**Comment by whtowbin** [comment]
This example clears it all up for me.
 I had been trying to make it using subplots. 
I misinterpreted the if statements for plot_area_profile. Line 872 of the profiles module mentions setting show_water_ppm = False so I assumed that my failure to get it to show up was result of that but I was mistaken. 
Thanks
