### ISSUE TITLE
getting peak fits for composite peaks

### ISSUE THREAD

**Issue by barthac** [EFerriss/Pynams#32]
I'm trying to get peak fits that I've made and for some reason the composite peaks I've made are behaving strangely:

![screen shot 2017-11-20 at 10 25 20 am](https://user-images.githubusercontent.com/21955716/33026854-74f9599c-cddf-11e7-953c-b18873f69485.png)

I've gone into the excel file and it seems to have made and saved the composite peak (idx = 10) fine.

**Comment by EFerriss** [comment]
It looks like all of your new peak areas are equal to zero, so matplotlib is mad at you because the program is trying to set the top of the y-axis (a bit more than the maximum value, which is zero) so close to the bottom (zero). Check your_profile.peak_areas[10] has the right numbers.

**Comment by barthac** [comment]
Indeed, it gives me zero: 
array([ 0.,  0.,  0.,  0.,  0.,  0.])

Any idea why the area would be zero? 

The excel sheet shows finite peak height and width:

peak position   (wavenumber /cm) | height (/cm) | width of gaussian (/cm)
-- | -- | --
3232 | 0.56 | 85
3328 | 1.54 | 30
3358 | 0.44 | 20
3390 | 0.22 | 40
3453 | 0.05 | 30
3487 | 0 | 25
3524 | 0.26 | 33
3545 | 0.05 | 10
3559 | 0.05 | 11
3572 | 0.26 | 12
6686 | 1.98 | 50
7096 | 0.52 | 45

**Comment by barthac** [comment]
The composite peaks are 
6686
7096

**Comment by EFerriss** [comment]
Hmmm. You might need to run some sort of area getting function. Check profile.peak_heights[10] and profile.peak_widths[10] look right.

**Comment by EFerriss** [comment]
I'm guessing you made these numbers in a spreadsheet outside of pynams and then go grab them, but pynams doesn't know to convert those into areas, so we'll have to add that in somewhere.

**Comment by barthac** [comment]
Yes, peak heights and widths look good

**Comment by EFerriss** [comment]
First please tell me what this does:
print(profile.spectra[0].peak_areas[10]

**Comment by EFerriss** [comment]
Then try this:

for spec in profile.spectra:
      spec.make_peakareas()
profile.make_areas(peak=10)
print(profile.peak_areas[10])

**Comment by EFerriss** [comment]
indent the spec.make_peakareas()

**Comment by barthac** [comment]
print(profile.spectra[0].peak_areas[10]) gives 0

**Comment by barthac** [comment]
The loop gives the following:

peak at 10
No peak at wavenumber 10
peak positions: [3232.0, 3328.0, 3358.0, 3390.0, 3453.0, 3487.0, 3524.0, 3545.0, 3559.0, 3572.0, 6686.0, 7096.0, 6686.0, 7096.0]
[ 0.  0.  0.  0.  0.  0.]

**Comment by barthac** [comment]
So I guess it thinks that 10 is the wavenumber not the index?

**Comment by EFerriss** [comment]
Right, sorry, try inputting the correct wavenumber

**Comment by barthac** [comment]
Now I get this: 

peak at 6686
[ 0.  0.  0.  0.  0.  0.]

**Comment by EFerriss** [comment]
Why isn't it able to calculate the area properly?

Try print(profile.peak_areas). Is it getting everything else correct but not that one composite peak?

**Comment by EFerriss** [comment]
I'm assuming print(profile.spectra[0].peak_areas[10]) even after running make_peakareas on that spectrum and for that peak.

**Comment by barthac** [comment]
printing all peak areas gives:

[[ 50.52100979  54.12965334  57.7382969   59.54261868  61.34694046
   61.34694046]
 [ 49.04029937  48.40341237  48.40341237  48.40341237  48.40341237
   47.76652536]
 [  9.34092169   9.34092169   9.34092169   9.34092169   9.34092169
    9.34092169]
 [  9.34098425   9.34098425   9.34098425   9.34098425   9.34098425
    9.34098425]
 [  1.59221128   1.59221128   1.59221128   1.59221128   1.59221128
    1.59221128]
 [  0.           0.           0.           0.           0.           0.        ]
 [  9.10744852   9.10744852   9.10744852   9.10744852   9.10744852
    9.10744852]
 [  0.53073709   0.53073709   0.53073709   0.53073709   0.53073709
    0.53073709]
 [  0.5838108    0.5838108    0.5838108    0.5838108    0.5838108
    0.5838108 ]
 [  3.31179946   3.31179946   3.31179946   3.31179946   3.31179946
    3.31179946]
 [  0.           0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.           0.        ]
 [ 58.38122106  57.74433406  57.74433406  57.74433406  57.74433406
   57.10744705]
 [ 12.41924798  12.41924798  12.41924798  12.41924798  12.41924798
   12.41924798]]

**Comment by EFerriss** [comment]
So it's having trouble making the areas for peak indexes 5, 10, and 11. What is special about those?

**Comment by EFerriss** [comment]
Can you show me profile.peak_heights and profile.peak_widths too please?

**Comment by barthac** [comment]
5 might actually have been set to zero
10 and 11 are the composite Tri and Ti peaks.
12 and 13 shouldn't be there... I only made 2 composite peaks. Seems like it has done that twice

**Comment by barthac** [comment]
Peak heights:

[[ 0.56  0.6   0.64  0.66  0.68  0.68]
 [ 1.54  1.52  1.52  1.52  1.52  1.5 ]
 [ 0.44  0.44  0.44  0.44  0.44  0.44]
 [ 0.22  0.22  0.22  0.22  0.22  0.22]
 [ 0.05  0.05  0.05  0.05  0.05  0.05]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.26  0.26  0.26  0.26  0.26  0.26]
 [ 0.05  0.05  0.05  0.05  0.05  0.05]
 [ 0.05  0.05  0.05  0.05  0.05  0.05]
 [ 0.26  0.26  0.26  0.26  0.26  0.26]
 [ 1.98  1.96  1.96  1.96  1.96  1.94]
 [ 0.52  0.52  0.52  0.52  0.52  0.52]
 [ 1.98  1.96  1.96  1.96  1.96  1.94]
 [ 0.52  0.52  0.52  0.52  0.52  0.52]]

**Comment by barthac** [comment]
Widths:

[[ 85.  85.  85.  85.  85.  85.]
 [ 30.  30.  30.  30.  30.  30.]
 [ 20.  20.  20.  20.  20.  20.]
 [ 40.  40.  40.  40.  40.  40.]
 [ 30.  30.  30.  30.  30.  30.]
 [ 25.  25.  25.  25.  25.  25.]
 [ 33.  33.  33.  33.  33.  33.]
 [ 10.  10.  10.  10.  10.  10.]
 [ 11.  11.  11.  11.  11.  11.]
 [ 12.  12.  12.  12.  12.  12.]
 [ 50.  50.  50.  50.  50.  50.]
 [ 45.  45.  45.  45.  45.  45.]
 [ 50.  50.  50.  50.  50.  50.]
 [ 45.  45.  45.  45.  45.  45.]]

**Comment by EFerriss** [comment]
I think happened is that somewhere you ran the make_composite_peak lines twice, so now it's in there twice, and it only made the areas once, so your peak_idx 12 has your areas for peak_idx 10, and your peak_idx 13 has the ones that should be in peak_idx 11

**Comment by EFerriss** [comment]
This is a bug that showed up because the program assumes that the same peak wavenumber is only present once, but you have shown that is not necessarily true. I think I can fix it.

**Comment by EFerriss** [comment]
If you print(profile.peakpos) you will see the list of peak wavenumbers

**Comment by barthac** [comment]
I think you're right. But I just restarted the Kernal and cleared output, and now get this for peak areas:

[[ 50.52100979  54.12965334  57.7382969   59.54261868  61.34694046
   61.34694046]
 [ 49.04029937  48.40341237  48.40341237  48.40341237  48.40341237
   47.76652536]
 [  9.34092169   9.34092169   9.34092169   9.34092169   9.34092169
    9.34092169]
 [  9.34098425   9.34098425   9.34098425   9.34098425   9.34098425
    9.34098425]
 [  1.59221128   1.59221128   1.59221128   1.59221128   1.59221128
    1.59221128]
 [  0.           0.           0.           0.           0.           0.        ]
 [  9.10744852   9.10744852   9.10744852   9.10744852   9.10744852
    9.10744852]
 [  0.53073709   0.53073709   0.53073709   0.53073709   0.53073709
    0.53073709]
 [  0.5838108    0.5838108    0.5838108    0.5838108    0.5838108
    0.5838108 ]
 [  3.31179946   3.31179946   3.31179946   3.31179946   3.31179946
    3.31179946]
 [  0.           0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.           0.        ]]

**Comment by barthac** [comment]
So it is not making peaks 12 and 13 anymore. But still can't make 10 and 11

**Comment by EFerriss** [comment]
Do
for spec in profile.spectra:
spec.make_peakareas()

and then print out profile.peak_areas again

**Comment by barthac** [comment]
I did, it doesn't change anything

**Comment by EFerriss** [comment]
Curiouser and curiouser.

Try making the composite peaks again and see if the areas for index 12 and 13 come up

**Comment by barthac** [comment]
Yes, it makes them again:

[[ 50.52100979  54.12965334  57.7382969   59.54261868  61.34694046
   61.34694046]
 [ 49.04029937  48.40341237  48.40341237  48.40341237  48.40341237
   47.76652536]
 [  9.34092169   9.34092169   9.34092169   9.34092169   9.34092169
    9.34092169]
 [  9.34098425   9.34098425   9.34098425   9.34098425   9.34098425
    9.34098425]
 [  1.59221128   1.59221128   1.59221128   1.59221128   1.59221128
    1.59221128]
 [  0.           0.           0.           0.           0.           0.        ]
 [  9.10744852   9.10744852   9.10744852   9.10744852   9.10744852
    9.10744852]
 [  0.53073709   0.53073709   0.53073709   0.53073709   0.53073709
    0.53073709]
 [  0.5838108    0.5838108    0.5838108    0.5838108    0.5838108
    0.5838108 ]
 [  3.31179946   3.31179946   3.31179946   3.31179946   3.31179946
    3.31179946]
 [  0.           0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.           0.        ]
 [ 58.38122106  57.74433406  57.74433406  57.74433406  57.74433406
   57.10744705]
 [ 12.41924798  12.41924798  12.41924798  12.41924798  12.41924798
   12.41924798]]

**Comment by barthac** [comment]
And yet, if I try to plot peak #12 it gives me an empty plot...

**Comment by EFerriss** [comment]
Really? That's distressing.

**Comment by EFerriss** [comment]
print(profile.spectra[0].peak_areas[12])

**Comment by barthac** [comment]
Gives me 0

**Comment by barthac** [comment]
So weird!!

**Comment by barthac** [comment]
I think I need to get rid of the imaginary peaks at 10 and 11. But I don't know how to do that -- any ideas?

**Comment by EFerriss** [comment]
Ok, so it's getting confused about where to put the data. 

print(profile.spectra[0].peak_areas[10])

**Comment by barthac** [comment]
Gives 0 also

**Comment by EFerriss** [comment]
Alright, I want to play with it. Please email me the spectrum, baseline and peakfit file that you are using.

**Comment by EFerriss** [comment]
It's clever what you've thought to do - put all the peakfit info in a file and then go get it, but the code isn't set up to handle that yet.

**Comment by barthac** [comment]
I just manually deleted the peakfit files and then remade them and the composite peaks and now works fine.

**Comment by EFerriss** [comment]
So it works when you run make_composite_peak but does not work when you include the composite peaks in your peakfit file?

**Comment by barthac** [comment]
Yes! I just saved the composite peaks in the peak fit file, then re got the peak fits and it gives zero areas for 10 and 11 again.

**Comment by barthac** [comment]
Darn, I'm late to a very early lunch with the geodynamics speaker. Will send you the files in case you want to play

**Comment by EFerriss** [comment]
Please do send

**Comment by barthac** [comment]
Just sent. Off to lunch but will be back online by 12.30

**Comment by EFerriss** [comment]
The update I just push should solve this issue, but let me know if there is still a problem.

**Comment by barthac** [comment]
This works! Thanks Elizabeth!
