### ISSUE TITLE
Plotting initials along with time series for WB

### ISSUE THREAD

**Issue by barthac** [EFerriss/Pynams#33]
Having a little difficulty working out how to plot my initial profiles on the same plot as the 30 min data. 
I have made two separate 'blocks'. One with the initial profiles, one with the 30 min data and am trying to plot them on the same graph using 'axes3 = list_of_3_axes'. 
Checked that the areas for the two blocks are indeed different so they should be plotting on top of each other.

My plotting code looks like this: 

fig, list_of_3_axes = ETFS_Init_Ea.plot_diffusion(time_seconds=3*3600.,labelD=False,
                                                       wholeblock_data=True, wholeblock_diffusion=True,
                           style_data={'color': 'r'})

ETFS_30min_Ea.plot_diffusion(axes3=list_of_3_axes, time_seconds=3*3600.,labelDy=0.2,
                                                       wholeblock_data=True, wholeblock_diffusion=True,
                                                  style_data={ 'color': 'b'})

**Comment by EFerriss** [comment]
What is the error message? Or is the second group just not showing up? Does the second block of data plot ok when you are not trying to put it on the same group of 3 axes?

**Comment by EFerriss** [comment]
Try using block.plot_areas_3panels() instead of plot_diffusion() just to start with.

**Comment by EFerriss** [comment]
I also just realized there isn't a clear example for the initial profiles in the example notebook. I'll work on that.

**Comment by EFerriss** [comment]
I bet it's getting confused because it doesn't know what the initial profiles are supposed to be for making the whole block code.

**Comment by barthac** [comment]
There is no error message, just second group doesn't plot. Second block of data plots fine on its own graph.

**Comment by barthac** [comment]
They both plot on the same graph if I use plot_areas_3panels() instead

**Comment by EFerriss** [comment]
I think you can use plot_areas_3panels() and then add the diffusion curve with plot_diffusion(show_data=False) to get what you want.

**Comment by EFerriss** [comment]
Let me know how that goes. I also added some clarification, especially about specifying each profile's initial_profile, [in the examples](https://github.com/EFerriss/Pynams/blob/master/EXAMPLES_diffusion3D.ipynb).

**Comment by barthac** [comment]
The new example is very helpful! Thanks!
