### ISSUE TITLE
Plotting Arrhenius diagram

### ISSUE THREAD

**Issue by barthac** [EFerriss/Pynams#35]
How do I add legend entries to the legend for the arrhenius diagram using diffusion.diffusivities.Arrhenius_add_line() ?
It doesn't accept a label. 

/Users/annabarth/Desktop/Screen Shot 2018-02-11 at 10.07.52 AM.png

Also, is there an easy way to get the activation energies and Do from the literature and plot them on the arrhenius diagram?

Thanks!

**Comment by EFerriss** [comment]
You are so deep in the weeds of pynams, I am amazed!! 

I think you have to pass in the legend handles as an argument somewhere or else it won't know where to put the legend entries? Honestly, this functionality never worked quite as well as I wanted it to, and I don't use it much. Maybe you will clean that up and help out others, including your future self? 

Legends are great for quick stuff, but in most publications you'll probably end up just sticking the label on yourself anyway, so the legend functionality is pretty low priority. Access to literature values is more important, and all of that data is in a spreadsheet in or near the same folder. You might not have the updated version, so check out the updates I just pushed. Also maybe useful for you to check out [the code from the Arrhenius diagram of the paper I just submitted](https://github.com/EFerriss/olivine/blob/master/olivine/Fig12_ArrheniusDiagram.py).

**Comment by EFerriss** [comment]
I was thinking about this some more, and what I actually use for this kind of exploratory analysis is [this interactive arrhenius diagram](https://arrheniusdiagram.herokuapp.com/arrheniusdiagram). The code for that is available [here](https://github.com/EFerriss/arrheniusdiagram), so you could grab that code, add your data to the csv file in there, and then run it locally. You could even add your data on and update the online plot when you're ready to publish. Ideally that csv would link up with the one in pynams, but for now they're just copied between repositories.

**Comment by EFerriss** [comment]
Also, your screen shot doesn't show up on my computer.

**Comment by barthac** [comment]
I actually ended up using the code in your 'Olivine' module. Really easy to
manipulate.
Love the interactive one for playing around with!
I'll add my arrhenius fits once I've played around with them a bit more.

**Comment by EFerriss** [comment]
great!

**Comment by EFerriss** [comment]
Also - going forward, if you and Henry decide to clean up the code and drop out legacy stuff that no one would possibly use anymore, that Arrhenius diagram code is very delete-able, and then maybe link to my olivine figure or this issue note in one of the example notebooks for later people looking for Arrhenius diagram examples.
