### ISSUE TITLE
Version 0.8.0 of lmfit causing module not found error

### ISSUE THREAD

**Issue by asp2201** [EFerriss/Pynams#41]
Hi Elizabeth! I'm just getting started using pynams to process my FTIR spectra and am having trouble using pip to install the module. I believe this is due to the version of lmfit in the setup.py file (0.8.0)– it's causing a module not found error:

> Collecting pynams
>   Using cached pynams-0.2.3-py3-none-any.whl (77 kB)
> Collecting lmfit==0.8.0 (from pynams)
>   Using cached lmfit-0.8.0.tar.gz (799 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [24 lines of output]
>       Traceback (most recent call last):
>         File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r2/9hg81w5n0bb_lrxdwf9dgcm80000gn/T/pip-build-env-lv7xcg1u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r2/9hg81w5n0bb_lrxdwf9dgcm80000gn/T/pip-build-env-lv7xcg1u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
>           self.run_setup()
>         File "/private/var/folders/r2/9hg81w5n0bb_lrxdwf9dgcm80000gn/T/pip-build-env-lv7xcg1u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
>           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
>         File "/private/var/folders/r2/9hg81w5n0bb_lrxdwf9dgcm80000gn/T/pip-build-env-lv7xcg1u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
>           exec(code, locals())
>         File "<string>", line 5, in <module>
>         File "/private/var/folders/r2/9hg81w5n0bb_lrxdwf9dgcm80000gn/T/pip-install-j10wxs9d/lmfit_2da8aaf3af7f41fb83fe9e435e8c3c96/lmfit/__init__.py", line 38, in <module>
>           from .minimizer import minimize, Minimizer, MinimizerException
>         File "/private/var/folders/r2/9hg81w5n0bb_lrxdwf9dgcm80000gn/T/pip-install-j10wxs9d/lmfit_2da8aaf3af7f41fb83fe9e435e8c3c96/lmfit/minimizer.py", line 15, in <module>
>           import numpy as np
>       ModuleNotFoundError: No module named 'numpy'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

I downloaded the package and changed the setup.py file to be for lmfit version 0.8.3, and that seemed to work. Would it be possible to update the setup file here so I could still use pip to install the module? Thanks!

**Comment by EFerriss** [comment]
Done!

**Comment by EFerriss** [comment]
I probably have to figure out how to update it on pypi though, not just here, will work on that next

**Comment by EFerriss** [comment]
Yeah, that's gonna be a slightly bigger project, will try to get to it this weekend. Sorry about the delay

**Comment by EFerriss** [comment]
@asp2201 I updated it on pypi, so hopefully pip should work. Let me know how it goes!

**Comment by asp2201** [comment]
That worked– thanks very much!! :)
