### ISSUE TITLE
Separate Baseline vs Peak Area Interval 

### ISSUE THREAD

**Issue by whtowbin** [EFerriss/Pynams#7]
Hi Elizabeth, I was thinking it might be helpful to be able to specify another interval for the area calculation from the baseline. This might be better for low concentrations where the spectra gets noisy and you need to use the abs-smear function with a wide interval. Let me know if you need me to offer more info or test anything out.

**Comment by EFerriss** [comment]
You should be able to do this now by setting the wn_low and wn_high keywords in spectrum.get_area_under_curve() and profile.make_area_list()

**Comment by whtowbin** [comment]
Works great thanks for setting it up!
